spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lvbohan2003
logging:
  level:
    com.itheima: debug
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
knife4j:
  enable: true
  production: false
  basic:
    openapi:
      enable: true
      title: 用户管理接口文档
      description: 用户管理接口文档
      email: zhanghuyi@itcast.com
      concat: 虎哥
      url: https://www.itcast.com
      version: 1.0.0
      group:
        default:
          group-name: default
          api-rule: package
          api-rule-resources:
            - com.itheima.mp.controller
